server:
  port: 8080

spring:
  application:
    name: Stydu4
  datasource:
    url: "jdbc:mysql://localhost:3306/stydu5"
    username: root
    password: luong123
  jpa:
    database: mysql
    hibernate:
      #ddl-auto: none
      #ddl-auto: create
      ddl-auto: update
      #ddl-auto: create-drop
    properties:
        format_sql: true
    show-sql: true
  data:
    redis:
      host: localhost
      port: 6379
      database: 0
jwt:
  signerKey: "cxwHya1whYAEv/LiFOjn928sU0kL/F953Ba2TLePb+tCM5usAtSnIMGXE2QYNIpb"


