server:
  port: 8080

spring:
  application:
    name: Stydu4
  datasource:
    url: "jdbc:mysql://localhost:3306/stydu4"
    username: root
    password: luong123
  jpa:
    database: mysql
    hibernate:
      #ddl-auto: none
      #ddl-auto: create
      ddl-auto: update
      #ddl-auto: create-drop
    properties:
        format_sql: true
    show-sql: true


